#!/bin/bash

# Update rules for where apps should launch
~/.config/bspwm/scripts/set_desktop_rules.sh "duplicate"

# Rerender lockscreen image
betterlockscreen -u ~/Pictures/Wallpapers/main.jpg --fx dimblur &

# Set desktops for the remaining monitor
bspc monitor "$(bspc query -M --names)" -d 1 2 3 4 5 6 7 8 9 10

# Set wallpaper
feh --bg-scale /home/eric/Pictures/Wallpapers/main.jpg &

sleep 3

# Restart polybar
~/.config/polybar/launch_one.sh
