#!/bin/bash

# Move all desktops except the default to the primary monitor
for desktop in $(bspc query -D --names | sed '/Desktop/d'); do
  bspc desktop "$desktop" --to-monitor $(xrandr | grep primary | sed 's/ .*//')
done

# Reorder desktops
bspc monitor $(xrandr | grep primary | sed 's/ .*//') -o 1 2 3 4 5 6 7 8 9 10 Desktop

# Restart polybar
sleep 5 # wait in case monitor was connect but status hasn't changed yet
~/.config/polybar/launch.sh

# Set wallpaper
feh --bg-scale /home/eric/Pictures/Wallpapers/main.jpg &
