#!/bin/bash

sleep 3

monitors=""
monitor_order_file=~/.config/autorandr/$(autorandr | grep 'current' | awk '{print $1;}')_order

# Rerender lockscreen image
betterlockscreen -u ~/Pictures/Wallpapers/main.jpg --fx dimblur &

# Set desktops for all monitor outputs
for monitor in $(xrandr --listmonitors | sed 1d | awk '{print $NF}'); do
  monitors+="$monitor "
  bspc monitor "$monitor" -d 1 2 3 4 5 6 7 8 9 10
done

# Order the monitors
if test -s $monitor_order_file; then
  bspc wm -O $(cat $monitor_order_file)
else
  bspc wm -O $monitors
fi

# Set wallpaper
feh --bg-scale /home/eric/Pictures/Wallpapers/main.jpg &

# Workaround for bspwm desktop bounds shrinking
bspc config right_padding 0
bspc config bottom_padding 0

# Restart polybar
~/.config/polybar/launch.sh
