#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Set desktops for all monitor outputs
for monitor in $(xrandr --listmonitors | sed 1d | awk '{print $NF}'); do
  bspc monitor "$monitor" -d 1 2 3 4 5 6 7 8 9 10
done

bspc config border_width         2
bspc config window_gap          12

bspc config pointer_motion_interval 7 # 144 hz window movement

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a thunderbird desktop='^1:^1'
bspc rule -a "*:crx_kjbdgfilnfhdoflbpgamdcdgpehopbep" desktop='^1:^1'
bspc rule -a "*:crx_mgamiaabcidhdjkgbmmalofnegcnbbpi" desktop='^1:^2'
bspc rule -a discord desktop='^1:^2'
bspc rule -a Lutris desktop='^1:^5'
bspc rule -a Steam desktop='^1:^5'
bspc rule -a zoom state=floating

# Border
bspc config focused_border_color        "#61afef"
bspc config normal_border_color         "#282c34"
bspc config active_border_color         "#282c34"
bspc config presel_feedback_color       "#aab2bf"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
feh --bg-scale /home/eric/Pictures/Wallpapers/main.jpg &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
picom -b &
# Network Applet
nm-applet --indicator &
# IMWHeel for scrolling
imwheel -b "45" &
# Cursor
xsetroot -cursor_name left_ptr &
# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh &
# Set single window in a workspace to have normal_border_color
~/.config/bspwm/scripts/single_window_color.sh &
# Workaround for electron and chrome window focusing bug
~/.config/bspwm/scripts/electron_fix.sh &
# Lock and suspend on idle. IdleActionSec in logind.conf doesn't work correctly
# without a display manager so it is handled here
betterlockscreen -u ~/Pictures/Wallpapers/main.jpg --fx dimblur &
xidlehook \
  --detect-sleep \
  --timer 120 'light -O;light -S 5' 'light -I' \
  --timer 420 'betterlockscreen -l dimblur' 'light -I' \
  --timer 660 'light -I;systemctl suspend' '' &
